version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: solupg-postgres
    environment:
      POSTGRES_USER: solupg
      POSTGRES_PASSWORD: solupg_dev
      POSTGRES_DB: solupg
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: solupg-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
